### ISSUE TITLE
Anonymous role isn't available

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/simple_access_grants#15] opened 2017-06-25 20:47 UTC
I need to control access to some node types for anonymous users.

After the installation of *Simple Access Grants* and a rebuild of the permissons I can change the access settings for the "Authenticated" and the "Administrator" roles but I don't see any option for the "Anonymous" role. Is this by design, or is something not working on my site?

**Comment by olafgrabienski** [comment] 2017-06-25 21:05
I just realized that I can accomplish the task to control *view* access to some node types using the [Content view access](https://backdropcms.org/project/content_view_access) module, and that's exactly what I need for the moment.

So feel free to close this issue. I'm however interested in the question if the lacking "Anonymous" role in the settings of *Simple Access Grants* is by design. (I imagine it's because there are the options "Update" and "Delete" which shouldn't be granted to anonymous users.)

**Comment by Graham-72** [comment] 2017-06-26 05:26
I am interested in your question and I am trying to imagine a scenario in which one might want to use this module to control access for anonymous viewers. I think the answer to your question is that the lack of this is by design, because of the way the underlying node access control works.

If this module is used to control access to a specific node type then all users including anonymous are barred from access unless their role is specifically granted access. If one were then able to grant access to anonymous users would this not be the same as removing the node type from any access restriction?

Or are you envisaging a situation in which certain node types are only intended for viewing by anonymous viewers and will not be displayed to certain roles if they are logged in?

I apologise for not understanding your requirement and I would like a bit more explanation please.

**Comment by olafgrabienski** [comment] 2017-06-26 09:28
> If this module is used to control access to a specific node type then all users including anonymous are barred from access unless their role is specifically granted access.

I see, that's all I wanted! Before, I didn't realize that it works that way. So, thanks for the explanation, @Graham-72!

**Comment by Retsell** [comment] 2019-11-06 00:15
> If this module is used to control access to a specific node type then all users including anonymous are barred from access unless their role is specifically granted access. If one were then able to grant access to anonymous users would this not be the same as removing the node type from any access restriction?

Yes, this is what is needed.  I want at least one content type to be accessible to Anonymous users. To see any other content types then they need to be authorized.  But if I can't enable at least one content type then they can't see anything on the site.  I want them to see a home page, which will inform them of the need to register before they can see anything else.

**Comment by Graham-72** [comment] 2019-11-06 07:55
@Retsell you don't have to 'enable' content types for anonymous users. They are 'enabled' for all content types that do not have an access restriction set.  So you could have your home page as an unrestricted type of node and use restricted content types for everything else. Nodes are unrestricted unless a setting has been applied.

**Comment by Retsell** [comment] 2020-10-13 16:35
Sorry for delayed response on this, but want to thank @Graham-72  for the additional clarification. What I was looking for was a way to make a different home page for anonymous users vs. logged-in users.  But then realized that Conditions can accomplish that just fine.

**Comment by Graham-72** [comment] 2020-10-15 14:02
I think this issue has now been answered and so I am closing it.

**Closed as completed by Graham-72** 2020-10-15 14:02 UTC
